### ISSUE TITLE
Correct installation for an Ember Addon

### ISSUE THREAD

**Issue by roomman** [NullVoxPopuli/eslint-configs#124]
Hi and thanks for this package, which I hope will help me out of lint config hell!

Just installed this into an Ember Addon. All works well in the Addon itself but I am seeing an error in .js files in the dummy app: 
```
Parsing error: The keyword 'import' is reserved
```
I followed your docs and added the following the `./.eslintrc` and `./tests/. eslintrc`:
```
'use strict';
const { configs } = require('@nullvoxpopuli/eslint-configs');
module.exports = configs.ember();
```
Have I missed a step in terms of setting up for linting the dummy app?

**Comment by NullVoxPopuli** [comment]
Hello!!! <3

You should be able to delete the `./tests/.eslintrc` file, the root eslint covers tests.

does your file end with .js or .cjs?
do you have a stack trace for your keyword import is reserved error?

**Comment by roomman** [comment]
Amazing, thanks for the speedy reply!

Removing `./tests/.eslintrc` was enough to sort it out. 

For info, it was in `./tests/dummy/app/router.js`. 

Thanks again 🙏🏼
