### ISSUE TITLE
babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser

### ISSUE THREAD

**Issue by oliverlj** [NullVoxPopuli/eslint-configs#66]
warning babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

Just got this warning on yarn install

**Comment by NullVoxPopuli** [comment]
Thanks for the tip!

Thin package should probably use the typescript parser for everything, because @babel/eslint-parser doesn't support native classes yet. 
ie:
