### ISSUE TITLE
Question: relative override paths ?

### ISSUE THREAD

**Issue by oliverlj** [NullVoxPopuli/eslint-configs#78]
I just updated to 3.28 and ember cli upgrade path to relalative path as shown in the next commit

https://github.com/ember-cli/ember-cli/commit/eef31df15662e137828f10f980bd7877b226a16d

Just wonder if needed to this addon ?

**Comment by NullVoxPopuli** [comment]
Probably. I believe the relative paths prevent matching of files under the name name, but in nested folders: https://github.com/NullVoxPopuli/eslint-configs/blob/main/configs/ember.js#L116
